"""Where each battle sound comes from: what ships, or what you put there.

Every sound a battle makes is generated by bin/make-battle-audio and
committed, so a fresh clone fights with sound and with nothing in it that
anybody else wrote. Any of them can be replaced without touching the
repository by dropping a file of the same name into

    $XDG_CONFIG_HOME/omarchy/hyprbattles/assets/

That directory is deliberately outside the checkout: a clone stays clean, and
`git status` stays quiet, however much music is in it.

Three modes decide which of the two directories wins:

    auto        a custom file when there is one, otherwise the generated one.
                Per file, so replacing only the theme leaves the other five
                alone. The default.
    generated   only what ships, even when a custom file is sitting there.
                This is the A/B position: it needs no files moved.
    custom      only what you supplied. A name you have not supplied is
                silent, which is what makes this different from `auto` and
                what makes it a real test of your own set.

The mode is a file, `$XDG_STATE_HOME/hyprscroll2d/battles-assets`, the same
shape as the on/off flag beside it - so it can be read and written with the
daemon stopped. `HYPRBATTLES_ASSETS` overrides it for one process, which
is how a single run is tried without changing the saved setting.

Nothing here does I/O beyond `stat`, and every entry point takes its
directories and its environment as arguments, so the resolution order can be
tested without a home directory.
"""

import os

PLUGIN_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# What ships: generated by bin/make-battle-audio, committed.
GENERATED = os.path.join(PLUGIN_ROOT, "assets")

ENV_VAR = "HYPRBATTLES_ASSETS"
MODES = ("auto", "generated", "custom")
DEFAULT_MODE = "auto"

# Every name the daemon ever asks for, in the order `battles-ctl assets`
# prints them: the music first, then the one-shots.
SOUNDS = ("battle-theme.wav", "battle-select.wav", "battle-hit.wav",
          "battle-heal.wav", "battle-levelup.wav", "battle-victory.wav",
          "battle-defeat.wav")


def custom_dir(environ=None):
    """Where a user's own files live. Outside the repository, on purpose."""
    environ = os.environ if environ is None else environ
    config_home = (environ.get("XDG_CONFIG_HOME")
                   or os.path.join(os.path.expanduser("~"), ".config"))
    return os.path.join(config_home, "omarchy", "hyprbattles", "assets")


def mode_path(environ=None):
    """The saved mode, beside the on/off flag rather than in the checkout."""
    environ = os.environ if environ is None else environ
    state_home = (environ.get("XDG_STATE_HOME")
                  or os.path.join(os.path.expanduser("~"), ".local", "state"))
    return os.path.join(state_home, "hyprscroll2d", "battles-assets")


def saved_mode(environ=None, path=None):
    """What the state file says, ignoring the environment.

    Separate from mode() so `battles-ctl assets` can say "custom, because
    HYPRBATTLES_ASSETS says so" rather than leaving someone to wonder why
    the setting they saved is not the setting in force.
    """
    environ = os.environ if environ is None else environ
    try:
        with open(path if path is not None else mode_path(environ)) as handle:
            saved = handle.read().strip().lower()
    except OSError:
        return DEFAULT_MODE
    return saved if saved in MODES else DEFAULT_MODE


def override_mode(environ=None):
    """The one-run override, or None. Anything unrecognised is None rather
    than an error: a typo in a shell profile should not take the sound out."""
    environ = os.environ if environ is None else environ
    wanted = (environ.get(ENV_VAR) or "").strip().lower()
    return wanted if wanted in MODES else None


def mode(environ=None, path=None):
    """auto | generated | custom, as it actually applies.

    The environment variable wins, because it is the one-run override; then
    the saved file; then `auto`.
    """
    environ = os.environ if environ is None else environ
    return override_mode(environ) or saved_mode(environ, path)


def set_mode(wanted, environ=None, path=None):
    """Save the mode. Returns the error string, or None on success."""
    if wanted not in MODES:
        return "unknown assets mode: %s (want %s)" % (wanted, ", ".join(MODES))
    environ = os.environ if environ is None else environ
    target = path if path is not None else mode_path(environ)
    try:
        os.makedirs(os.path.dirname(target), exist_ok=True)
        with open(target, "w") as handle:
            handle.write(wanted + "\n")
    except OSError as error:
        return "cannot save the assets mode: %s" % error
    return None


def resolve(name, which=None, generated=None, custom=None, environ=None):
    """The file this sound actually plays from, or None for silence.

    `which` is the mode; left out, it is looked up. The fallback is per name,
    not per set, so a custom theme and five generated one-shots is an ordinary
    state rather than a half-configured one.
    """
    environ = os.environ if environ is None else environ
    which = mode(environ) if which is None else which
    generated = GENERATED if generated is None else generated
    custom = custom_dir(environ) if custom is None else custom

    if which != "generated":
        candidate = os.path.join(custom, name)
        if os.path.exists(candidate):
            return candidate
        if which == "custom":
            return None
    candidate = os.path.join(generated, name)
    return candidate if os.path.exists(candidate) else None


def directories(generated=None, custom=None, environ=None):
    """Both places a battle sound can come from, for anything that has to
    sweep or watch them rather than open one file."""
    environ = os.environ if environ is None else environ
    return (GENERATED if generated is None else generated,
            custom_dir(environ) if custom is None else custom)


def resolution(which=None, generated=None, custom=None, environ=None,
               names=SOUNDS):
    """What every sound resolves to, for `battles-ctl assets` to print.

    A list of (name, path or None, "generated" | "custom" | "missing"), which
    is the answer to "why is my file not playing".
    """
    environ = os.environ if environ is None else environ
    which = mode(environ) if which is None else which
    generated, custom = directories(generated, custom, environ)
    rows = []
    for name in names:
        path = resolve(name, which, generated, custom, environ)
        if path is None:
            source = "missing"
        elif os.path.dirname(path) == custom:
            source = "custom"
        else:
            source = "generated"
        rows.append((name, path, source))
    return rows
